import { useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'

type Distro = { name:string; slug:string; description:string; base:string; desktop:string; arch:string; size:string; categories:string[]; logo:string; download:string; site:string; docs:string }

const distros:Distro[] = [
['Ubuntu','ubuntu','A polished Debian-based Linux distribution for desktops, servers, and broad hardware support.','Debian','GNOME','x86_64 / ARM64','~5 GB',['beginner','desktop','gaming','server'],'https://assets.ubuntu.com/v1/29985a98-ubuntu-logo32.png','https://ubuntu.com/download/desktop','https://ubuntu.com/','https://help.ubuntu.com/'],
['Linux Mint','linux-mint','A comfortable desktop Linux distribution focused on simplicity and an easy transition from Windows.','Ubuntu / Debian','Cinnamon','x86_64','~3 GB',['beginner','desktop','lightweight'],'https://www.linuxmint.com/web/img/logo.png','https://www.linuxmint.com/download.php','https://www.linuxmint.com/','https://linuxmint.com/documentation.php'],
['Fedora','fedora','A community-driven distribution showcasing current Linux technologies and developer tooling.','Independent','GNOME','x86_64 / ARM64','~3 GB',['desktop','gaming','server'],'https://fedoraproject.org/assets/images/logos/fedora-blue.png','https://fedoraproject.org/workstation/download/','https://fedoraproject.org/','https://docs.fedoraproject.org/'],
['Debian','debian','A stable, universal operating system and a foundation of the wider Linux ecosystem.','Independent','GNOME / KDE / XFCE','x86_64 / ARM64 / ARMHF','Varies',['server','desktop','lightweight'],'https://www.debian.org/logos/openlogo-nd-75.jpg','https://www.debian.org/download','https://www.debian.org/','https://www.debian.org/doc/'],
['Arch Linux','arch','A minimal rolling-release distribution built around simplicity, user control, and extensive documentation.','Independent','Choose your own','x86_64','~1 GB',['rolling','lightweight','gaming'],'https://archlinux.org/static/logos/archlinux-logo-light-scalable.svg','https://archlinux.org/download/','https://archlinux.org/','https://wiki.archlinux.org/'],
['Manjaro','manjaro','An accessible Arch-based distribution with curated desktop editions and rolling releases.','Arch','XFCE / KDE / GNOME','x86_64 / ARM64','~3 GB',['rolling','gaming','beginner'],'https://manjaro.org/img/logo.svg','https://manjaro.org/products/download/x86','https://manjaro.org/','https://wiki.manjaro.org/'],
['Pop!_OS','pop-os','A productivity-focused Ubuntu-based distribution with a polished workflow and strong hardware support.','Ubuntu','COSMIC','x86_64','~3 GB',['gaming','desktop','beginner'],'https://system76.com/_next/static/media/popos-logo.1b4e2b3c.svg','https://system76.com/pop/download/','https://system76.com/pop/','https://support.system76.com/'],
['Zorin OS','zorin','An Ubuntu-based desktop distribution built to make Linux feel familiar, fast, and approachable.','Ubuntu','Zorin Desktop','x86_64','~3 GB',['beginner','desktop','lightweight'],'https://assets.zorincdn.com/images/logo/zorin-icon.svg','https://zorin.com/os/download/','https://zorin.com/os/','https://help.zorin.com/'],
['Kali Linux','kali','A Debian-based security distribution packed with tools for penetration testing and security research.','Debian','XFCE','x86_64 / ARM64','~4 GB',['security','privacy'],'https://www.kali.org/images/kali-logo.svg','https://www.kali.org/get-kali/','https://www.kali.org/','https://www.kali.org/docs/'],
['openSUSE','opensuse','A powerful Linux ecosystem known for YaST, Btrfs tooling, and fixed or rolling releases.','Independent','KDE / GNOME','x86_64 / ARM64','~4 GB',['server','desktop','rolling'],'https://en.opensuse.org/images/4/49/Geeko-button.png','https://get.opensuse.org/','https://www.opensuse.org/','https://doc.opensuse.org/'],
['EndeavourOS','endeavouros','A lightweight Arch-based distribution keeping the Arch spirit with a friendly installer and community.','Arch','XFCE / KDE / GNOME+','x86_64 / ARM64','~2 GB',['rolling','lightweight','gaming'],'https://endeavouros.com/wp-content/uploads/2021/03/cropped-eos-logo.png','https://endeavouros.com/latest-release/','https://endeavouros.com/','https://discovery.endeavouros.com/'],
['MX Linux','mx-linux','A Debian-based desktop distribution focused on stability, efficiency, and practical administration tools.','Debian','XFCE','x86_64 / AHS','~2.5 GB',['lightweight','beginner','desktop'],'https://mxlinux.org/wp-content/uploads/2020/07/mx-logo.png','https://mxlinux.org/download-links/','https://mxlinux.org/','https://mxlinux.org/wiki/']
].map(x=>({name:x[0] as string,slug:x[1] as string,description:x[2] as string,base:x[3] as string,desktop:x[4] as string,arch:x[5] as string,size:x[6] as string,categories:x[7] as string[],logo:x[8] as string,download:x[9] as string,site:x[10] as string,docs:x[11] as string}))

const filters=[['All','all'],['Beginner Friendly','beginner'],['Lightweight','lightweight'],['Gaming','gaming'],['Privacy','privacy'],['Security','security'],['Server','server'],['Rolling Release','rolling']]

function App(){
 const [q,setQ]=useState(''),[filter,setFilter]=useState('all'),[selected,setSelected]=useState<Distro|null>(null),[light,setLight]=useState(false)
 const shown=useMemo(()=>distros.filter(d=>(filter==='all'||d.categories.includes(filter))&&(!q||[d.name,d.description,d.desktop,d.base,d.categories.join(' ')].join(' ').toLowerCase().includes(q.toLowerCase()))),[q,filter])
 const random=()=>setSelected(distros[Math.floor(Math.random()*distros.length)])
 return <div className={light?'app light':'app'}>
  <nav><a className="brand" href="#top"><span>🐧</span> DistroOnTheBase</a><div className="navlinks"><a href="#distros">Distributions</a><a href="#wizard">Wizard</a><a href="https://github.com/leoyeoh-netizen/DOTB" target="_blank">GitHub ↗</a><button onClick={()=>setLight(!light)}>{light?'☾':'☀'} Theme</button></div></nav>
  <header id="top"><div className="eyebrow">● OPEN SOURCE · OFFICIAL DOWNLOAD LINKS</div><h1>Your Linux Downloads,<br/><em>All in One Place.</em></h1><p>Browse and download popular Linux distributions from one centralized, open-source hub. No accounts. No popups. Just the distro you came for.</p><div className="searchrow"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search Linux distributions..."/><button onClick={random} className="secondary">⤨ Random Distro</button></div><div className="filters">{filters.map(([label,v])=><button className={filter===v?'active':''} onClick={()=>setFilter(v)} key={v}>{label}</button>)}</div></header>
  <main id="distros"><div className="sectionhead"><div><small>BROWSE</small><h2>Linux distributions</h2><p>{shown.length} projects matching your filters</p></div></div><div className="grid">{shown.map(d=><article className="card" key={d.slug} onClick={()=>setSelected(d)}><div className="cardtop"><div className="logo"><img src={d.logo} onError={e=>(e.currentTarget.style.display='none')} /></div><div><h3>{d.name}</h3><span>{d.base} · {d.desktop}</span></div></div><p>{d.description}</p><div className="meta"><span>{d.arch}</span><span>{d.size}</span></div><div className="actions"><a href={d.download} target="_blank" onClick={e=>e.stopPropagation()}>Download ↗</a><button onClick={e=>{e.stopPropagation();setSelected(d)}}>Details</button></div></article>)}</div>{!shown.length&&<div className="empty">No distributions found. Try a broader search.</div>}
  <section id="wizard" className="wizard"><small>DISTRO WIZARD</small><h2>Find distributions that match your needs.</h2><p>Choose criteria and explore matching projects. The wizard is informational, not a universal “best distro” machine.</p><div className="wizardgrid"><select id="goal"><option value="beginner">Beginner friendly</option><option value="gaming">Gaming</option><option value="security">Security</option><option value="lightweight">Lightweight</option><option value="server">Server</option><option value="rolling">Rolling release</option></select><div className="matches">{distros.filter(d=>d.categories.includes((document.getElementById('goal') as HTMLSelectElement)?.value||'beginner')).slice(0,4).map(d=><button key={d.slug} onClick={()=>setSelected(d)}>{d.name}</button>)}</div></div></section></main>
  <footer><span>© 2026 DistroOnTheBase</span><span>Independent project · Linux trademarks belong to their respective owners.</span><a href="https://github.com/leoyeoh-netizen/DOTB" target="_blank">Source on GitHub ↗</a></footer>
  {selected&&<div className="modal" onClick={()=>setSelected(null)}><div className="dialog" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><div className="cardtop"><div className="logo"><img src={selected.logo}/></div><div><h2>{selected.name}</h2><span>{selected.base} · {selected.desktop}</span></div></div><p className="description">{selected.description}</p><div className="detailgrid"><div><small>ARCHITECTURE</small><b>{selected.arch}</b></div><div><small>ISO SIZE</small><b>{selected.size}</b></div><div><small>DOWNLOAD SOURCE</small><b>Official portal / mirror</b></div></div><div className="modalactions"><a href={selected.download} target="_blank">Download ISO ↗</a><a href={selected.site} target="_blank">Official Website ↗</a><a href={selected.docs} target="_blank">Documentation ↗</a></div><p className="note">DistroOnTheBase does not re-host ISO files. Downloads point to official distribution sources or recognized mirrors.</p></div></div>}
 </div>
}

createRoot(document.getElementById('root')!).render(<App />)
